import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "katex/dist/katex.min.css";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Firefly_IV Blog",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

// 全局主题初始化脚本：在 React hydration 之前同步执行，
// 读取 localStorage 决定 data-theme，避免 FOUC（首屏闪烁）
// 同时为所有路由（/blog、/tag 等）提供一致的全局主题
const themeInitScript = `
(function() {
  try {
    var k = 'wiki-theme';
    var s = localStorage.getItem(k);
    if (!s) {
      // 首次访问：跟随系统偏好
      s = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
    }
    document.documentElement.dataset.theme = s;
  } catch (e) {
    document.documentElement.dataset.theme = 'light';
  }
})();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
