import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Serif_SC, Noto_Sans_SC, Orbitron } from "next/font/google";
import "katex/dist/katex.min.css";
import "./globals.css";
import { MeteorBackground } from "./components/meteor-background";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Orbitron：科幻几何字体，用于开屏主标题与品牌标识（SIL OFL 1.1 开源协议）
const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: ["500", "700", "900"],
  display: "swap",
});

// 思源宋体：正文阅读（SIL OFL 1.1 开源协议，无版权风险）
// CJK 字体在 next/font 中不提供 chinese-simplified 子集，改用 latin + preload: false
// 中文字符仍会按需加载，不影响实际渲染
const notoSerif = Noto_Serif_SC({
  variable: "--font-serif-sc",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
  preload: false,
});

// 思源黑体：标题层级（SIL OFL 1.1 开源协议，无版权风险）
const notoSans = Noto_Sans_SC({
  variable: "--font-sans-sc",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
  preload: false,
});

export const metadata: Metadata = {
  title: "Firefly_IV Blog",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

// 全局主题初始化脚本：在 React hydration 之前同步执行，
// 读取 localStorage 决定 data-theme，避免 FOUC（首屏闪烁）
// 同时为所有路由（/blog、/tag 等）提供一致的全局主题
const themeInitScript = `
(function() {
  try {
    var k = 'wiki-theme';
    var s = localStorage.getItem(k);
    if (!s) {
      // 首次访问：跟随系统偏好
      s = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
    }
    document.documentElement.dataset.theme = s;
    // 精细指针设备启用自定义光标（SVG data URI，见 globals.css）
    if (window.matchMedia('(pointer: fine)').matches) {
      document.documentElement.classList.add('use-ani-cursor');
    }
  } catch (e) {
    document.documentElement.dataset.theme = 'light';
  }
})();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      data-scroll-behavior="smooth"
      className={`${geistSans.variable} ${geistMono.variable} ${notoSerif.variable} ${notoSans.variable} ${orbitron.variable} h-full antialiased`}
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body className="min-h-full flex flex-col">
        <MeteorBackground />
        {children}
      </body>
    </html>
  );
}
